apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-ingress-host.yaml
images:
  - name: docker.io/pavanrapolu16/ai-task-backend
    newTag: staging-latest
  - name: docker.io/pavanrapolu16/ai-task-worker
    newTag: staging-latest
  - name: docker.io/pavanrapolu16/ai-task-frontend
    newTag: staging-latest
