apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-ingress-host.yaml
images:
  - name: docker.io/your-dockerhub-username/ai-task-backend
    newTag: 2a837ea69cf23cc8f420cd5825c5f390bdc54b81
  - name: docker.io/your-dockerhub-username/ai-task-worker
    newTag: 2a837ea69cf23cc8f420cd5825c5f390bdc54b81
  - name: docker.io/your-dockerhub-username/ai-task-frontend
    newTag: 2a837ea69cf23cc8f420cd5825c5f390bdc54b81
