apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-production
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-task-platform
  source:
    repoURL: https://github.com/pavanrapolu16/infra-repo
    targetRevision: main
    path: overlays/production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
